### ISSUE TITLE
client要不从这个project分离出来，去耦合

### ISSUE THREAD

**Issue by inclyc** [hit-mc/pypsmb#10]

**Comment by keuin** [comment]
拆成俩子目录？比如`import psmb.client`和`psmb.server`这种。
其实我以前写的psmb client也在咱们组织里（我刚发现）：https://github.com/hit-mc/pybc
pybc里有消息encode和decode的实现，把客户端都拆到那边也可以。

**Comment by inclyc** [comment]
我新开一个pypsmb-client的包，然后我维护那个包吧。https://github.com/hit-mc/pybc 这个client好像还是Redis版的，不是psmb协议啊
